# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Northglenn HS Coding Club
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Website for the Coding Club at Northglenn High School
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nhscoding.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  NHSCoding14-15

# Build settings
markdown: kramdown
